
const { createClient } = require('@supabase/supabase-js');
require('dotenv').config();

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);

async function setupSmsTable() {
  console.log('Setting up SMS Inbox table...');

  const createTableQuery = `
    CREATE TABLE IF NOT EXISTS sms_inbox (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      device_id TEXT NOT NULL,
      sender TEXT,
      message TEXT,
      received_at TIMESTAMPTZ DEFAULT NOW()
    );
  `;

  const { error } = await supabase.rpc('exec_sql', { sql: createTableQuery });
  
  // If RPC fails (often does on some Supabase setups without specific function), 
  // we might need to rely on the user running SQL. 
  // But since we are using the JS client, we can't run raw DDL easily without a helper function.
  // However, we can try to just use the table if it exists, or assume the user will run it.
  // Actually, for this environment, I'll just add the SQL to a file and ask the user to run it 
  // OR I'll use the "logs" table for now to store SMS?
  // No, a separate table is better.
  
  // Let's try to use the standard "create if not exists" via a dummy insert or just print the SQL.
  // Since I can't execute DDL via supabase-js client directly without a stored procedure,
  // I will create a SQL file for the user.
  
  console.log('SQL to run in Supabase SQL Editor:');
  console.log(createTableQuery);
}

setupSmsTable();
