const { Client } = require('pg');

// Configuration using the details you provided
const client = new Client({
  user: 'postgres',
  host: 'db.ugsaejlogfychombnhgf.supabase.co',
  database: 'postgres',
  password: 'Papaji@GPS',
  port: 5432,
  ssl: { rejectUnauthorized: false } // Required for Supabase connections
});

async function setupDatabase() {
  try {
    console.log('Connecting to Supabase PostgreSQL...');
    await client.connect();
    console.log('Connected!');

    // 1. Enable PostGIS (for advanced location math)
    console.log('Enabling PostGIS...');
    await client.query('CREATE EXTENSION IF NOT EXISTS postgis;');

    // 2. Create the tracking_history table
    console.log('Creating table tracking_history...');
    await client.query(`
      CREATE TABLE IF NOT EXISTS tracking_history (
        id bigint generated by default as identity primary key,
        device_id text not null,
        latitude float not null,
        longitude float not null,
        speed float,
        battery float,
        created_at timestamp with time zone default timezone('utc'::text, now()) not null
      );
    `);

    // 3. Enable Realtime
    console.log('Enabling Realtime...');
    try {
      await client.query('alter publication supabase_realtime add table tracking_history;');
    } catch (e) {
      // Ignore error if table is already in publication
      if (!e.message.includes('already exists')) {
        console.log('Note on Realtime:', e.message);
      }
    }

    // 4. Configure Security (RLS) so your API Key works
    console.log('Configuring Security Policies...');
    await client.query(`
      ALTER TABLE tracking_history ENABLE ROW LEVEL SECURITY;
      
      -- Allow inserting data (for your ESP32/Backend)
      DROP POLICY IF EXISTS "Enable insert for everyone" ON tracking_history;
      CREATE POLICY "Enable insert for everyone" ON tracking_history FOR INSERT WITH CHECK (true);

      -- Allow reading data (for your App)
      DROP POLICY IF EXISTS "Enable read for everyone" ON tracking_history;
      CREATE POLICY "Enable read for everyone" ON tracking_history FOR SELECT USING (true);
    `);

    console.log('✅ SUCCESS: Database setup complete!');
    console.log('Table created and security policies applied.');

  } catch (err) {
    console.error('❌ ERROR:', err);
  } finally {
    await client.end();
  }
}

setupDatabase();
