-- Run this in your Supabase SQL Editor

-- 1. Create GPS Logs Table
CREATE TABLE IF NOT EXISTS gps_logs (
    id bigint generated by default as identity primary key,
    device_id text not null,
    latitude double precision not null,
    longitude double precision not null,
    speed double precision,
    battery double precision,
    signal int,
    hdop double precision,
    satellites int,
    created_at timestamptz default now()
);

-- 2. Create GSM Logs Table
CREATE TABLE IF NOT EXISTS gsm_logs (
    id bigint generated by default as identity primary key,
    device_id text not null,
    latitude double precision not null,
    longitude double precision not null,
    accuracy double precision, -- GSM accuracy in meters
    battery double precision,
    signal int,
    created_at timestamptz default now()
);

-- 3. Indexes for fast querying
CREATE INDEX IF NOT EXISTS idx_gps_device_time ON gps_logs(device_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_gsm_device_time ON gsm_logs(device_id, created_at DESC);
